version: "3.8"
services:
  app:
    container_name: user-list
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongodb:27017/user-list
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

  redis:
    container_name: redis
    image: redis:latest
